name: RUN TESTS
on:
  pull_request:
    branches: develop
    types: [synchronize, opened]

jobs:
  build:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --dev
      - name: Run Test
        run: yarn test
        env:
          CI: true
